<!-- Time-stamp: <2017-03-10 12:21:42 (slane)> -->

---
title: "Censored MLE Investigation"
author: Stephen E. Lane
date: `r format(Sys.Date(), format = '%B %d, %Y')`
output: html_document
---

## Testing

In this document, I detail the investigation into performing a censored regression on the *blistering barnacles* (otherwise known as *biofouling*) project. This document and the ensuing analyses should be seen as exploratory, not definitive. The main reason for this document is to have notes and code/output interspersed, rather than existing as random bits of paper everywhere!

## Idea

So, the idea for this project is to test the effect of certain variables on the measured wet weight of biofouling on boats. Measurements are taken in different locations (e.g. hull, propeller).

Complicating the analysis is that the scales used for measuring the wet weight have a limit of detection of 1.5gm. That is, any measurements under 1.5gm are unreliable and are thus censored. So, to take this into account, we need to have a model that adjusts for the probability of censoring; that is, the model adjusts for the probability that a measurement will be less than 1.5gm.
